### ISSUE TITLE
mate-applets-1.20.0 fails to install

### ISSUE THREAD

**Issue by NeddySeagoon** [bunder2015/overlay#1]
On arm64 mate-applets-1.20.0 fails to install.
The build log is ugly but here it is, https://paste.pound-python.org/show/xig27MEfhPUeojD0NS1M/

>>> Source compiled.
>>> Test phase [not enabled]: mate-base/mate-applets-1.20.0

>>> Install mate-applets-1.20.0 into /var/tmp/portage/mate-base/mate-applets-1.20.0/image/ category mate-base
find: 'invest-applet': No such file or directory
 * ERROR: mate-base/mate-applets-1.20.0::bunder failed (install phase):
 *   (no error message)

**Comment by NeddySeagoon** [comment]
Removing both references to invest-applet in mate-applets-1.20.0.ebuild allows it to build.
invest-applet is missing of course, so its not really a fix.

**Comment by bunder2015** [comment]
yep, i just noticed that.  it's been fixed.
